hotkey: "cmd+esc"

messages:
  starting: "âš™ï¸ getting things ready, wait a moment..."
  ready: "âœ… hold <cmd+esc> to talk to ALTS"
  textInput: "> "
  listening: "ğŸ™ï¸ listening..."
  transcribing: "ğŸ’¬ transcribing..."
  thinking: "ğŸ’­ processing your request..."
  speaking: "ğŸ”Š responding to you..."

whisper:
  model: "tiny"
  isMulti: false

llm:
  url: "http://localhost:11434"
  model: "ollama/dolphin-phi"
  system: "You are ALTS, a helpful AI assistant. Your responses are limited to the user's questions. Stick to the questions. Be concise. Avoid verbosity when possible"
  custom_provider: ""

tts:
  model: "tts_models/en/vctk/vits"
  speakerId: "p364"
